// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REST_API;

#nullable disable

namespace REST_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250803161123_improveDB")]
    partial class improveDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("REST_API.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Arpan Dev",
                            Description = "A beginner's guide to C#",
                            Name = "C# Programming",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Arpan Dev",
                            Description = "Learn to build APIs with ASP.NET Core",
                            Name = "ASP.NET Core Web API",
                            Price = 34.99m
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Julie Lerman",
                            Description = "Master Entity Framework Core",
                            Name = "EF Core In Action",
                            Price = 32.50m
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Joe Smith",
                            Description = "Learn LINQ from basics to advanced",
                            Name = "LINQ Fundamentals",
                            Price = 27.00m
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "John Taylor",
                            Description = "Create modern websites with Razor Pages",
                            Name = "ASP.NET Razor Pages",
                            Price = 23.49m
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Robert C. Martin",
                            Description = "Write maintainable and readable code",
                            Name = "Clean Code",
                            Price = 42.95m
                        },
                        new
                        {
                            Id = 7,
                            AuthorName = "Arpan Dev",
                            Description = "Classic design patterns with C#",
                            Name = "Design Patterns in C#",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 8,
                            AuthorName = "Jane Doe",
                            Description = "Concurrency and parallelism in C#",
                            Name = "Multithreading in C#",
                            Price = 35.75m
                        },
                        new
                        {
                            Id = 9,
                            AuthorName = "Mark Allen",
                            Description = "Practical data structures for developers",
                            Name = "Data Structures",
                            Price = 31.99m
                        },
                        new
                        {
                            Id = 10,
                            AuthorName = "Arpan Dev",
                            Description = "Test your .NET code with xUnit",
                            Name = "Unit Testing with xUnit",
                            Price = 28.95m
                        },
                        new
                        {
                            Id = 11,
                            AuthorName = "Sam Hill",
                            Description = "Build scalable microservices",
                            Name = "Microservices with .NET",
                            Price = 43.99m
                        },
                        new
                        {
                            Id = 12,
                            AuthorName = "Lara Hughes",
                            Description = "Protect your apps from common threats",
                            Name = "Web Security Essentials",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 13,
                            AuthorName = "Arpan Dev",
                            Description = "Build interactive UIs with Blazor",
                            Name = "Blazor in Depth",
                            Price = 37.20m
                        },
                        new
                        {
                            Id = 14,
                            AuthorName = "Rahul Patel",
                            Description = "Best practices for designing RESTful APIs",
                            Name = "REST API Design",
                            Price = 30.10m
                        },
                        new
                        {
                            Id = 15,
                            AuthorName = "Alice Moore",
                            Description = "Improve and optimize legacy code",
                            Name = "Refactoring C# Code",
                            Price = 41.99m
                        },
                        new
                        {
                            Id = 16,
                            AuthorName = "Tom Johnson",
                            Description = "Version control using Git and GitHub",
                            Name = "Git for Developers",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 17,
                            AuthorName = "Emily Zhang",
                            Description = "Comparison of two data access strategies",
                            Name = "Dapper vs EF Core",
                            Price = 26.95m
                        },
                        new
                        {
                            Id = 18,
                            AuthorName = "Arpan Dev",
                            Description = "Real-time features with SignalR",
                            Name = "SignalR Real-time Apps",
                            Price = 33.00m
                        },
                        new
                        {
                            Id = 19,
                            AuthorName = "Brian Lee",
                            Description = "How to log and monitor .NET apps",
                            Name = "Logging in ASP.NET",
                            Price = 21.99m
                        },
                        new
                        {
                            Id = 20,
                            AuthorName = "Arpan Dev",
                            Description = "Hidden gems and performance tricks",
                            Name = "Advanced C# Tips",
                            Price = 36.45m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
